# Generated by Django 4.0.5 on 2022-06-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_restaurants_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='coordinates',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='neighborhood',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='yelp_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
