# Generated by Django 4.0.5 on 2022-06-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_restaurant_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
